'\" t
.\"     Title: lttng-create
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 7 December 2021
.\"    Manual: LTTng Manual
.\"    Source: LTTng 2.13.7
.\"  Language: English
.\"
.TH "LTTNG\-CREATE" "1" "7 December 2021" "LTTng 2\&.13\&.7" "LTTng Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lttng-create \- Create an LTTng recording session
.SH "SYNOPSIS"
.sp
Create a local mode recording session:
.sp
.nf
\fBlttng\fR [\fIGENERAL OPTIONS\fR] \fBcreate\fR [\fISESSION\fR] [\fB--shm-path\fR=\fIDIR\fR]
      [\fB--no-output\fR | \fB--output\fR=\fIDIR\fR | \fB--set-url\fR=\fBfile://\fR\fIDIR\fR]
.fi
.sp
Create a network streaming mode recording session:
.sp
.nf
\fBlttng\fR [\fIGENERAL OPTIONS\fR] \fBcreate\fR [\fISESSION\fR] [\fB--shm-path\fR=\fIDIR\fR]
      (\fB--set-url\fR=\fIURL\fR | \fB--ctrl-url\fR=\fIURL\fR \fB--data-url\fR=\fIURL\fR)
.fi
.sp
Create a snapshot mode recording session:
.sp
.nf
\fBlttng\fR [\fIGENERAL OPTIONS\fR] \fBcreate\fR [\fISESSION\fR] \fB--snapshot\fR [\fB--shm-path\fR=\fIDIR\fR]
      [\fB--no-output\fR | \fB--output\fR=\fIDIR\fR | \fB--set-url\fR=\fIURL\fR |
       \fB--ctrl-url\fR=\fIURL\fR \fB--data-url\fR=\fIURL\fR]
.fi
.sp
Create a live mode recording session:
.sp
.nf
\fBlttng\fR [\fIGENERAL OPTIONS\fR] \fBcreate\fR [\fISESSION\fR] \fB--live\fR[=\fIDELAYUS\fR]
      [\fB--shm-path\fR=\fIDIR\fR] [\fB--set-url\fR=\fIURL\fR | \fB--ctrl-url\fR=\fIURL\fR \fB--data-url\fR=\fIURL\fR]
.fi
.SH "DESCRIPTION"
.sp
The \fBlttng create\fR command creates a new recording session for your Unix user within the connected session daemon (see the \(lqSession daemon connection\(rq section of \fBlttng\fR(1) to learn how a user application connects to a session daemon)\&.
.sp
See \fBlttng-concepts\fR(7) to learn more about recording sessions\&.
.sp
Without the \fISESSION\fR argument, LTTng automatically generates a recording session name having the \fBauto-\fR\fIYYYYmmdd\fR\fB-\fR\fIHHMMSS\fR form, where \fIYYYYmmdd\fR and \fIHHMMSS\fR are the creation date and time\&. \fISESSION\fR may NOT contain the character \fB/\fR\&.
.sp
Specify the path of the directory containing the shared memory files holding the channel ring buffers with the \fB--shm-path\fR option\&. Specifying a location on an NVRAM file system makes it possible to recover the latest recorded trace data when the system reboots after a crash with the \fBlttng-crash\fR(1) utility\&. Note that, as of LTTng\ \&2\&.13\&.7, this feature is only available for user space channels\&.
.sp
By default, the \fBcreate\fR command automatically spawns:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
A session daemon for your Unix user if none is currently running\&.
.sp
Override the path of the session daemon binary to spawn with the general
\fB--sessiond-path\fR
option\&.
.sp
Avoid automatically spawning a session daemon with the general
\fB--no-sessiond\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
A relay daemon (see
\fBlttng-relayd\fR(8)) if all the following statements are true:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
You specify the
\fB--live\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
You don\(cqt specify any of the
\fB--set-url\fR,
\fB--ctrl-url\fR, or
\fB--data-url\fR
options\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
No relay daemon is currently listening for TCP connections on
\fB127.0.0.1:5344\fR
(default LTTng live reader connection address and port)\&.
.RE
.sp
In this case, the
\fBcreate\fR
command spawns a relay daemon as such:
.sp
.if n \{\
.RS 4
.\}
.nf
\fBlttng\-relayd\fR \fB--live-port\fR=\fBtcp://localhost:5344\fR
\ \&
.fi
.if n \{\
.RE
.\}
Override the path of the relay daemon binary to spawn with the general
\fB--relayd-path\fR
option\&.
.RE
.sp
On success, the \fBcreate\fR command sets the current recording session (see \fBlttng-concepts\fR(7) to learn more) to the created recording session\&.
.sp
See the \(lqEXAMPLES\(rq section below for usage examples\&.
.sp
Show the status of the current recording session with the \fBlttng-status\fR(1) command\&.
.sp
List the recording sessions of your Unix user, or of all users if your Unix user is \fBroot\fR, within the connected session daemon with the \fBlttng-list\fR(1) command\&.
.sp
Start and stop a recording session with the \fBlttng-start\fR(1) and \fBlttng-stop\fR(1) commands\&.
.sp
Save and load a recording session with the \fBlttng-save\fR(1) and \fBlttng-load\fR(1) commands\&.
.sp
Allow and disallow specific processes to record events with the \fBlttng-track\fR(1) and \fBlttng-untrack\fR(1) commands\&.
.sp
Archive the current trace chunk of (rotate) a recording session with the \fBlttng-rotate\fR(1) command\&.
.sp
Destroy a recording session with the \fBlttng-destroy\fR(1) command\&.
.SS "Recording session modes"
.sp
As documented in \fBlttng-concepts\fR(7), LTTng offers four recording session modes:
.PP
Local mode
.RS 4
Write the trace data to the local file system\&.
.sp
The trace data output directory is:
.PP
With the \fB--no-output\fR option
.RS 4
None: the file system output is disabled\&.
.RE
.PP
With the \fB--output\fR=\fIDIR\fR or \fB--set-url\fR=\fBfile://\fR\fIDIR\fR option
.RS 4
The directory
\fIDIR\fR\&.
.RE
.PP
Otherwise
.RS 4
A subdirectory, under the
\fB$LTTNG_HOME/lttng-traces\fR
(\fB$LTTNG_HOME\fR
defaults to
\fB$HOME\fR) directory, of which the name contains the recording session name and the date/time\&.
.RE
.RE
.PP
Network streaming mode
.RS 4
Send the trace data over the network to a listening relay daemon (see
\fBlttng-relayd\fR(8))\&.
.sp
Set the trace output destination with the
\fB--set-url\fR
option, or with the
\fB--ctrl-url\fR
and
\fB--data-url\fR
options (see the \(lqURL format\(rq section below)\&.
.RE
.PP
Snapshot mode (\fB--snapshot\fR option)
.RS 4
Only write the trace data to the local file system or send it to a listening relay daemon (\fBlttng-relayd\fR(8)) when LTTng takes a snapshot (see the
\fBlttng-snapshot\fR(1)
command)\&.
.sp
With this mode, LTTng:
.PP
With the \fB--no-output\fR option
.RS 4
Does NOT add any snapshot output to the created recording session\&.
.RE
.PP
With the \fB--output\fR option, the \fB--set-url\fR option, or the \fB--ctrl-url\fR and \fB--data-url\fR options
.RS 4
Adds a snapshot output named
\fBsnapshot-1\fR
using the provided path or URL(s) to the created recording session\&.
.RE
.PP
Otherwise
.RS 4
Adds an automatic snapshot output named
\fBsnapshot-1\fR
to the created recording session\&.
.sp
The automatic snapshot output is a subdirectory, under the
\fB$LTTNG_HOME/lttng-traces\fR
(\fB$LTTNG_HOME\fR
defaults to
\fB$HOME\fR) directory, of which the name contains the recording session name and the date/time\&.
.RE
.RE
.PP
Live mode (\fB--live\fR option)
.RS 4
Send the trace data over the network to a listening relay daemon (see
\fBlttng-relayd\fR(8)) for live reading\&.
.sp
Set the trace output destination with the
\fB--set-url\fR=\fIURL\fR
option, or with the
\fB--ctrl-url\fR=\fIURL\fR
and
\fB--data-url\fR=\fIURL\fR
options (see the \(lqURL format\(rq section below)\&.
\fIURL\fR
may NOT start with
\fBfile://\fR\&.
.RE
.SS "URL format"
.sp
The argument of the \fB--set-url\fR=\fIURL\fR, \fB--ctrl-url\fR=\fIURL\fR, and \fB--data-url\fR=\fIURL\fR options is an URL\&.
.sp
There are two available \fIURL\fR formats\&.
.PP
Local format
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
file://\fITRACEDIR\fR
\ \&
.fi
.if n \{\
.RE
.\}
The
\fBfile://\fR
protocol targets the
\fBlocal file system\fR: you may only use such an URL with the
\fB--set-url\fR
option when you create the recording session in local or snapshot mode (see the \(lqRecording session modes\(rq section above)\&.
.PP
\fITRACEDIR\fR
.RS 4
Absolute path to the directory containing the trace data on the local file system\&.
.RE
.RE
.PP
Network format
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fINETPROTO\fR://(\fIHOST\fR | \fIIPADDR\fR)[:\fICTRLPORT\fR[:\fIDATAPORT\fR]][/\fITRACEDIR\fR]
\ \&
.fi
.if n \{\
.RE
.\}
This format is only available when you create the recording session in network streaming, snapshot (\fB--snapshot\fR), or live (\fB--live\fR) mode (see the \(lqRecording session modes\(rq section above)\&.
.PP
\fINETPROTO\fR
.RS 4
Network protocol, amongst:
.PP
\fBnet\fR
.RS 4
TCP over IPv4\&.
.sp
The default values of
\fICTRLPORT\fR
and
\fIDATAPORT\fR
are respectively 5342 and 5343\&.
.RE
.PP
\fBnet6\fR
.RS 4
TCP over IPv6\&.
.sp
The default values of
\fICTRLPORT\fR
and
\fIDATAPORT\fR
are respectively 5342 and 5343\&.
.RE
.PP
\fBtcp\fR
.RS 4
Same as the
\fBnet\fR
protocol\&.
.sp
You may only use this with the
\fB--ctrl-url\fR
and
\fB--data-url\fR
options together\&.
.RE
.PP
\fBtcp6\fR
.RS 4
Same as the
\fBnet6\fR
protocol\&.
.sp
You can only be use this with the
\fB--ctrl-url\fR
and
\fB--data-url\fR
options together\&.
.RE
.RE
.PP
(\fIHOST\fR | \fIIPADDR\fR)
.RS 4
Hostname or IP address\&.
.sp
IPv6 address must be enclosed in square brackets (\fB[\fR
and\ \&\fB]\fR); see
RFC\ \&2732 <https://www.ietf.org/rfc/rfc2732.txt>\&.
.RE
.PP
\fICTRLPORT\fR
.RS 4
Control TCP port\&.
.RE
.PP
\fIDATAPORT\fR
.RS 4
Data TCP port\&.
.RE
.PP
\fITRACEDIR\fR
.RS 4
Path of the directory containing the trace data on the remote file system\&.
.sp
This path is relative to the base output directory of the LTTng relay daemon (see the
\fB--output\fR
option of
\fBlttng-relayd\fR(8))\&.
.RE
.RE
.SH "OPTIONS"
.sp
See \fBlttng\fR(1) for \fIGENERAL OPTIONS\fR\&.
.SS "Mode selection"
.sp
See the \(lqRecording session modes\(rq section above\&.
.sp
At most one of:
.PP
\fB--live\fR[=\fIDELAYUS\fR]
.RS 4
Create the recording session in live mode\&.
.sp
The optional
\fIDELAYUS\fR
argument is the maximum time (in \(mcs) you can wait for the data to be flushed (sent to the connected LTTng relay daemon)\&. The default value of
\fIDELAYUS\fR
is 1000000\&.
.sp
Set the URL of the relay daemon to connect to with the
\fB--set-url\fR
option, or with the
\fB--ctrl-url\fR
and
\fB--data-url\fR
options, instead of using
\fBnet://127.0.0.1\fR\&.
.sp
The session daemon must be able to connect to a listening relay daemon (see
\fBlttng-relayd\fR(8))\&.
.RE
.PP
\fB--snapshot\fR
.RS 4
Create the recording session in snapshot mode\&.
.sp
This is equivalent to:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
One of:
.PP
With the \fB--no-output\fR option
.RS 4
Not adding any snapshot output after LTTng creates the recording session\&.
.RE
.PP
With the \fB--output\fR option, the \fB--set-url\fR option, or the \fB--ctrl-url\fR and \fB--data-url\fR options
.RS 4
Adding a snapshot output named
\fBsnapshot-1\fR
using the provided path or URL(s) immediately after LTTng creates the recording session\&.
.RE
.PP
Otherwise
.RS 4
Adding an automatic snapshot output named
\fBsnapshot-1\fR
immediately after LTTng creates the recording session\&.
.sp
The automatic snapshot output is a subdirectory, under the
\fB$LTTNG_HOME/lttng-traces\fR
(\fB$LTTNG_HOME\fR
defaults to
\fB$HOME\fR) directory, of which the name contains the recording session name and the date/time\&.
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Forcing all the channels to be created for the recording session to be configured with the
\fB--override\fR
and
\fB--output\fR=\fBmmap\fR
options (see
\fBlttng-enable-channel\fR(1))\&.
.RE
.RE
.SS "Output"
.PP
\fB--no-output\fR
.RS 4
Depending on the recording session mode (see the \(lqRecording session modes\(rq section above):
.PP
Local mode
.RS 4
Disable the file system output\&.
.RE
.PP
Snapshot mode (\fB--snapshot\fR option)
.RS 4
Do NOT add a snapshot output after creating the recording session\&.
.RE
.RE
.PP
\fB-o\fR \fIDIR\fR, \fB--output\fR=\fIDIR\fR
.RS 4
Equivalent to
\fB--set-url\fR=\fBfile://\fR\fIDIR\fR\&.
.RE
.PP
\fB--shm-path\fR=\fIDIR\fR
.RS 4
Set the path of the directory containing the shared memory files holding the channel ring buffers to
\fIDIR\fR
on the local file sytem\&.
.if n \{\
.sp
.\}
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.RS 4
As of LTTng\ \&2\&.13\&.7, LTTng only considers this option for user space (including Java and Python) channels, but this may change in the future\&.
.sp .5v
.RE
.RE
.SS "URL"
.sp
See the \(lqURL format\(rq section above to learn more about the syntax of the \fIURL\fR argument of the following options\&.
.PP
\fB-C\fR \fIURL\fR, \fB--ctrl-url\fR=\fIURL\fR
.RS 4
Set the control path URL to
\fIURL\fR\&.
.sp
You must also use the
\fB--data-url\fR
option\&.
.sp
Not available in local mode (see the \(lqRecording session modes\(rq section above)\&.
.sp
In snapshot mode, this is equivalent to using the
\fB--ctrl-url\fR
option of the
\fBadd-output\fR
action of the
\fBlttng-snapshot\fR(1)
command immediately after creating the recording session\&.
.RE
.PP
\fB-D\fR \fIURL\fR, \fB--data-url\fR=\fIURL\fR
.RS 4
Set the trace data path URL to
\fIURL\fR\&.
.sp
You must also use the
\fB--ctrl-url\fR
option\&.
.sp
Not available in local mode (see the \(lqRecording session modes\(rq section above)\&.
.sp
In snapshot mode, this is equivalent to using the
\fB--data-url\fR
option of the
\fBadd-output\fR
action of the
\fBlttng-snapshot\fR(1)
command immediately after creating the recording session\&.
.RE
.PP
\fB-U\fR \fIURL\fR, \fB--set-url\fR=\fIURL\fR
.RS 4
Set the destination URL of the control path and trace data to
\fIURL\fR\&.
.sp
This URL remains unchanged as long as the recording session exists\&.
.sp
Depending on the recording session mode (see the \(lqRecording session modes\(rq section above):
.PP
Local mode
.RS 4
\fIURL\fR
must start with
\fBfile://\fR, followed with the destination directory path on the local file system\&.
.RE
.PP
Network streaming and live modes
.RS 4
Equivalent to using both the
\fB--ctrl-url\fR
and
\fB--data-url\fR
options\&.
.RE
.PP
Snapshot mode (\fB--snapshot\fR option)
.RS 4
Equivalent to using the
\fIURL\fR
non\-option argument of the
\fBadd-output\fR
action of the
\fBlttng-snapshot\fR(1)
command immediately after creating the recording session\&.
.RE
.RE
.SS "Program information"
.PP
\fB-h\fR, \fB--help\fR
.RS 4
Show help\&.
.sp
This option attempts to launch
\fB/usr/bin/man\fR
to view this manual page\&. Override the manual pager path with the
\fBLTTNG_MAN_BIN_PATH\fR
environment variable\&.
.RE
.PP
\fB--list-options\fR
.RS 4
List available command options and quit\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Command error
.RE
.PP
\fB2\fR
.RS 4
Undefined command
.RE
.PP
\fB3\fR
.RS 4
Fatal error
.RE
.PP
\fB4\fR
.RS 4
Command warning (something went wrong during the command)
.RE
.SH "ENVIRONMENT"
.PP
\fBLTTNG_ABORT_ON_ERROR\fR
.RS 4
Set to
\fB1\fR
to abort the process after the first error is encountered\&.
.RE
.PP
\fBLTTNG_HOME\fR
.RS 4
Path to the LTTng home directory\&.
.sp
Defaults to
\fB$HOME\fR\&.
.sp
Useful when the Unix user running the commands has a non\-writable home directory\&.
.RE
.PP
\fBLTTNG_MAN_BIN_PATH\fR
.RS 4
Absolute path to the manual pager to use to read the LTTng command\-line help (with
\fBlttng-help\fR(1)
or with the
\fB--help\fR
option) instead of
\fB/usr/bin/man\fR\&.
.RE
.PP
\fBLTTNG_SESSION_CONFIG_XSD_PATH\fR
.RS 4
Path to the directory containing the
\fBsession.xsd\fR
recording session configuration XML schema\&.
.RE
.PP
\fBLTTNG_SESSIOND_PATH\fR
.RS 4
Absolute path to the LTTng session daemon binary (see
\fBlttng-sessiond\fR(8)) to spawn from the
\fBlttng-create\fR(1)
command\&.
.sp
The
\fB--sessiond-path\fR
general option overrides this environment variable\&.
.RE
.SH "FILES"
.PP
\fB$LTTNG_HOME/.lttngrc\fR
.RS 4
Unix user\(cqs LTTng runtime configuration\&.
.sp
This is where LTTng stores the name of the Unix user\(cqs current recording session between executions of
\fBlttng\fR(1)\&.
\fBlttng-create\fR(1)
and
\fBlttng-set-session\fR(1)
set the current recording session\&.
.RE
.PP
\fB$LTTNG_HOME/lttng-traces\fR
.RS 4
Default output directory of LTTng traces in local and snapshot modes\&.
.sp
Override this path with the
\fB--output\fR
option of the
\fBlttng-create\fR(1)
command\&.
.RE
.PP
\fB$LTTNG_HOME/.lttng\fR
.RS 4
Unix user\(cqs LTTng runtime and configuration directory\&.
.RE
.PP
\fB$LTTNG_HOME/.lttng/sessions\fR
.RS 4
Default directory containing the Unix user\(cqs saved recording session configurations (see
\fBlttng-save\fR(1)
and
\fBlttng-load\fR(1))\&.
.RE
.PP
\fB/usr/local/etc/lttng/sessions\fR
.RS 4
Directory containing the system\-wide saved recording session configurations (see
\fBlttng-save\fR(1)
and
\fBlttng-load\fR(1))\&.
.RE
.if n \{\
.sp
.\}
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.RS 4
.sp
\fB$LTTNG_HOME\fR defaults to the value of the \fBHOME\fR environment variable\&.
.sp .5v
.RE
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&Create a normal mode recording session with a generated name\&.\fR
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&2.\ \&Create a normal mode recording session with a custom name\&.\fR
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create my\-session
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&3.\ \&Create a normal mode recording session with a specific output directory\&.\fR
.RS 4
.sp
See the \fB--output\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-output=/path/to/traces
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&4.\ \&Create a network streaming mode recording session\&.\fR
.RS 4
.sp
See the \(lqOutput directory\(rq section of \fBlttng-relayd\fR(8) to understand where the relay daemon to connect to (\fB10.0.0.242\fR) writes the received traces\&.
.sp
See the \fB--set-url\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-set\-url=net://10\&.0\&.0\&.242/inv4
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&5.\ \&Create a snapshot mode recording session with a default snapshot output\&.\fR
.RS 4
.sp
See the \fB--snapshot\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-snapshot
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&6.\ \&Create a snapshot mode recording session with a custom snapshot output\&.\fR
.RS 4
.sp
See the \fB--snapshot\fR and \fB--set-url\fR options\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-snapshot \e
        \-\-set\-url=tcp://192\&.168\&.1\&.102:1234:5678/my\-snapshots
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&7.\ \&Create a snapshot mode recording session with no snapshot output\&.\fR
.RS 4
.sp
See the \fB--snapshot\fR and \fB--no-output\fR options\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-snapshot \-\-no\-output
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&8.\ \&Create an LTTng live mode recording session with a default relay daemon URL\&.\fR
.RS 4
.sp
See the \fB--live\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-live
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&9.\ \&Create an LTTng live mode recording session with a custom live timer period and relay daemon URL\&.\fR
.RS 4
.sp
See the \fB--live\fR and \fB--set-url\fR options\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create \-\-live=250000 \e
               \-\-set\-url=tcp://relayd34:4885:4886
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&10.\ \&Create a normal mode recording session with a custom directory containing the ring buffer shared memory files\&.\fR
.RS 4
.sp
See the \fB--shm-path\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng create my\-session \-\-shm\-path=/mnt/nvram2/lttng
.fi
.if n \{\
.RE
.\}
.RE
.SH "RESOURCES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTTng project website <https://lttng.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTTng documentation <https://lttng.org/docs>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTTng bug tracker <https://bugs.lttng.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Git repositories <https://git.lttng.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GitHub organization <https://github.com/lttng>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Continuous integration <https://ci.lttng.org/>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mailing list <https://lists.lttng.org/>
for support and development:
\fBlttng-dev@lists.lttng.org\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
IRC channel <irc://irc.oftc.net/lttng>:
\fB#lttng\fR
on
\fBirc.oftc.net\fR
.RE
.SH "COPYRIGHT"
.sp
This program is part of the LTTng\-tools project\&.
.sp
LTTng\-tools is distributed under the GNU General Public License version\ \&2 <http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html>\&. See the \fBLICENSE\fR <https://github.com/lttng/lttng-tools/blob/master/LICENSE> file for details\&.
.SH "THANKS"
.sp
Special thanks to Michel Dagenais and the DORSAL laboratory <http://www.dorsal.polymtl.ca/> at \('Ecole Polytechnique de Montr\('eal for the LTTng journey\&.
.sp
Also thanks to the Ericsson teams working on tracing which helped us greatly with detailed bug reports and unusual test cases\&.
.SH "SEE ALSO"
.sp
\fBlttng\fR(1), \fBlttng-destroy\fR(1), \fBlttng-enable-channel\fR(1), \fBlttng-list\fR(1), \fBlttng-rotate\fR(1), \fBlttng-save\fR(1), \fBlttng-set-session\fR(1), \fBlttng-start\fR(1), \fBlttng-status\fR(1), \fBlttng-track\fR(1), \fBlttng-concepts\fR(7), \fBlttng-relayd\fR(8), \fBlttng-sessiond\fR(8)
