'\" t
.\"     Title: lttng-disable-event
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 14 June 2021
.\"    Manual: LTTng Manual
.\"    Source: LTTng 2.13.6
.\"  Language: English
.\"
.TH "LTTNG\-DISABLE\-EVEN" "1" "14 June 2021" "LTTng 2\&.13\&.6" "LTTng Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lttng-disable-event \- Disable LTTng recording event rules
.SH "SYNOPSIS"
.sp
Disable one or more recording event rules matching Linux kernel events:
.sp
.nf
\fBlttng\fR [\fIGENERAL OPTIONS\fR] \fBdisable\-event\fR \fB--kernel\fR
      [\fB--tracepoint\fR | \fB--syscall\fR | \fB--probe\fR | \fB--function\fR]
      (\fB--all-events\fR | \fINAME\fR[,\fINAME\fR]\&...)
      [\fB--session\fR=\fISESSION\fR] [\fB--channel\fR=\fICHANNEL\fR]
.fi
.sp
Disable one or more recording event rules matching user space tracepoint or Java/Python logging events:
.sp
.nf
\fBlttng\fR [\fIGENERAL OPTIONS\fR] \fBdisable\-event\fR
      (\fB--userspace\fR | \fB--jul\fR | \fB--log4j\fR | \fB--python\fR) [\fB--tracepoint\fR]
      (\fB--all-events\fR | \fINAME\fR[,\fINAME\fR]\&...)
      [\fB--session\fR=\fISESSION\fR] [\fB--channel\fR=\fICHANNEL\fR]
.fi
.SH "DESCRIPTION"
.sp
The \fBlttng disable-event\fR command disables one or more enabled recording event rules previously created with the \fBlttng-enable-event\fR(1) command which belong to:
.PP
With the \fB--session\fR=\fISESSION\fR option
.RS 4
The recording session named
\fISESSION\fR\&.
.RE
.PP
Without the \fB--session\fR option
.RS 4
The current recording session (see
\fBlttng-concepts\fR(7)
to learn more about the current recording session)\&.
.RE
.PP
With the \fB--channel\fR=\fICHANNEL\fR option
.RS 4
The channel named
\fICHANNEL\fR\&.
.RE
.PP
Without the \fB--channel\fR option
.RS 4
The channel named
\fBchannel0\fR\&.
.sp
If there\(cqs more than one channel for the selected recording session and domain, the
\fBdisable-event\fR
command fails\&.
.RE
.sp
See \fBlttng-concepts\fR(7) to learn more about recording event rules\&.
.sp
As of LTTng\ \&2\&.13\&.6, the \fBdisable-event\fR command can only find recording event rules to disable by their instrumentation point type and event name conditions\&. Therefore, you cannot disable recording event rules having a specific instrumentation point log level condition, for example\&.
.sp
With the \fB--kernel\fR option and no instrumentation point type condition option, the \fBdisable-event\fR command disables one or more Linux kernel recording event rules regardless of their instrumentation point type\&.
.sp
List the recording event rules of a given recording session and/or channel with the \fBlttng-list\fR(1) command\&.
.sp
Without the \fB--all-events\fR option, the \fBdisable-event\fR command disables one recording event rule per \fINAME\fR argument\&. \fINAME\fR is the exact event name condition pattern of the recording event rule to disable, as listed in the output of \fBlttng list\fR (see \fBlttng-list\fR(1))\&.
.sp
You may disable an enabled recording event rule regardless of the activity (started or stopped) of its recording session (see \fBlttng-start\fR(1) and \fBlttng-stop\fR(1))\&.
.sp
See the \(lqEXAMPLES\(rq section below for usage examples\&.
.SH "OPTIONS"
.sp
See \fBlttng\fR(1) for \fIGENERAL OPTIONS\fR\&.
.SS "Tracing domain"
.sp
One of:
.PP
\fB-j\fR, \fB--jul\fR
.RS 4
Disable recording event rules in the
\fBjava.util.logging\fR
(JUL) domain\&.
.RE
.PP
\fB-k\fR, \fB--kernel\fR
.RS 4
Disable recording event rules in the Linux kernel domain\&.
.RE
.PP
\fB-l\fR, \fB--log4j\fR
.RS 4
Disable recording event rules in the Apache log4j domain\&.
.RE
.PP
\fB-p\fR, \fB--python\fR
.RS 4
Disable recording event rules in the Python domain\&.
.RE
.PP
\fB-u\fR, \fB--userspace\fR
.RS 4
Disable recording event rules in the user space tracing domain\&.
.RE
.SS "Recording target"
.PP
\fB-c\fR \fICHANNEL\fR, \fB--channel\fR=\fICHANNEL\fR
.RS 4
Disable recording event rules attached to the channel named
\fICHANNEL\fR
instead of
\fBchannel0\fR\&.
.RE
.PP
\fB-s\fR \fISESSION\fR, \fB--session\fR=\fISESSION\fR
.RS 4
Disable recording event rules in the recording session named
\fISESSION\fR
instead of the current recording session\&.
.RE
.SS "Instrumentation point type condition"
.sp
At most one of:
.PP
\fB--function\fR
.RS 4
Only disable recording event rules which match Linux kretprobe events\&.
.sp
Only available with the
\fB--kernel\fR
option\&.
.RE
.PP
\fB--probe\fR
.RS 4
Only disable recording event rules which match Linux kprobe events\&.
.sp
Only available with the
\fB--kernel\fR
option\&.
.RE
.PP
\fB--syscall\fR
.RS 4
Only disable recording event rules which match Linux system call events\&.
.sp
Only available with the
\fB--kernel\fR
option\&.
.RE
.PP
\fB--tracepoint\fR
.RS 4
Only disable recording event rules which match:
.PP
With the \fB--kernel\fR or \fB--userspace\fR option
.RS 4
LTTng tracepoint events\&.
.RE
.PP
With the \fB--jul\fR, \fB--log4j\fR, or \fB--python\fR option
.RS 4
Logging events\&.
.RE
.RE
.SS "Event name condition"
.PP
\fB-a\fR, \fB--all-events\fR
.RS 4
Disable recording event rules regardless of their event name condition\&.
.RE
.SS "Program information"
.PP
\fB-h\fR, \fB--help\fR
.RS 4
Show help\&.
.sp
This option attempts to launch
\fB/usr/bin/man\fR
to view this manual page\&. Override the manual pager path with the
\fBLTTNG_MAN_BIN_PATH\fR
environment variable\&.
.RE
.PP
\fB--list-options\fR
.RS 4
List available command options and quit\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Command error
.RE
.PP
\fB2\fR
.RS 4
Undefined command
.RE
.PP
\fB3\fR
.RS 4
Fatal error
.RE
.PP
\fB4\fR
.RS 4
Command warning (something went wrong during the command)
.RE
.SH "ENVIRONMENT"
.PP
\fBLTTNG_ABORT_ON_ERROR\fR
.RS 4
Set to
\fB1\fR
to abort the process after the first error is encountered\&.
.RE
.PP
\fBLTTNG_HOME\fR
.RS 4
Path to the LTTng home directory\&.
.sp
Defaults to
\fB$HOME\fR\&.
.sp
Useful when the Unix user running the commands has a non\-writable home directory\&.
.RE
.PP
\fBLTTNG_MAN_BIN_PATH\fR
.RS 4
Absolute path to the manual pager to use to read the LTTng command\-line help (with
\fBlttng-help\fR(1)
or with the
\fB--help\fR
option) instead of
\fB/usr/bin/man\fR\&.
.RE
.PP
\fBLTTNG_SESSION_CONFIG_XSD_PATH\fR
.RS 4
Path to the directory containing the
\fBsession.xsd\fR
recording session configuration XML schema\&.
.RE
.PP
\fBLTTNG_SESSIOND_PATH\fR
.RS 4
Absolute path to the LTTng session daemon binary (see
\fBlttng-sessiond\fR(8)) to spawn from the
\fBlttng-create\fR(1)
command\&.
.sp
The
\fB--sessiond-path\fR
general option overrides this environment variable\&.
.RE
.SH "FILES"
.PP
\fB$LTTNG_HOME/.lttngrc\fR
.RS 4
Unix user\(cqs LTTng runtime configuration\&.
.sp
This is where LTTng stores the name of the Unix user\(cqs current recording session between executions of
\fBlttng\fR(1)\&.
\fBlttng-create\fR(1)
and
\fBlttng-set-session\fR(1)
set the current recording session\&.
.RE
.PP
\fB$LTTNG_HOME/lttng-traces\fR
.RS 4
Default output directory of LTTng traces in local and snapshot modes\&.
.sp
Override this path with the
\fB--output\fR
option of the
\fBlttng-create\fR(1)
command\&.
.RE
.PP
\fB$LTTNG_HOME/.lttng\fR
.RS 4
Unix user\(cqs LTTng runtime and configuration directory\&.
.RE
.PP
\fB$LTTNG_HOME/.lttng/sessions\fR
.RS 4
Default directory containing the Unix user\(cqs saved recording session configurations (see
\fBlttng-save\fR(1)
and
\fBlttng-load\fR(1))\&.
.RE
.PP
\fB/usr/local/etc/lttng/sessions\fR
.RS 4
Directory containing the system\-wide saved recording session configurations (see
\fBlttng-save\fR(1)
and
\fBlttng-load\fR(1))\&.
.RE
.if n \{\
.sp
.\}
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.RS 4
.sp
\fB$LTTNG_HOME\fR defaults to the value of the \fBHOME\fR environment variable\&.
.sp .5v
.RE
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&Disable all Linux kernel tracepoint recording event rules in the default channel of the current recording session\&.\fR
.RS 4
.sp
See the \fB--all-events\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng disable\-event \-\-kernel \-\-tracepoint \-\-all\-events
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&2.\ \&Disable specific Apache log4j recording event rules in the default channel of a specific recording session\&.\fR
.RS 4
.sp
See the \fB--session\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng disable\-event \-\-session=my\-session \-\-log4j \e
                      MySingleton,MyProxy,MyFacade
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&3.\ \&Disable all user space recording event rules in a specific channel of the current recording session\&.\fR
.RS 4
.sp
See the \fB--channel\fR option\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng disable\-event \-\-channel=my\-channel \-\-userspace \e
                      \-\-all\-events
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample\ \&4.\ \&Disable specific Linux kernel system call recording event rules in the default channel of the current recording session\&.\fR
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
$ lttng disable\-event \-\-kernel \-\-syscall pipe2,eventfd
.fi
.if n \{\
.RE
.\}
.RE
.SH "RESOURCES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTTng project website <https://lttng.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTTng documentation <https://lttng.org/docs>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTTng bug tracker <https://bugs.lttng.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Git repositories <https://git.lttng.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GitHub organization <https://github.com/lttng>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Continuous integration <https://ci.lttng.org/>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mailing list <https://lists.lttng.org/>
for support and development:
\fBlttng-dev@lists.lttng.org\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
IRC channel <irc://irc.oftc.net/lttng>:
\fB#lttng\fR
on
\fBirc.oftc.net\fR
.RE
.SH "COPYRIGHT"
.sp
This program is part of the LTTng\-tools project\&.
.sp
LTTng\-tools is distributed under the GNU General Public License version\ \&2 <http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html>\&. See the \fBLICENSE\fR <https://github.com/lttng/lttng-tools/blob/master/LICENSE> file for details\&.
.SH "THANKS"
.sp
Special thanks to Michel Dagenais and the DORSAL laboratory <http://www.dorsal.polymtl.ca/> at \('Ecole Polytechnique de Montr\('eal for the LTTng journey\&.
.sp
Also thanks to the Ericsson teams working on tracing which helped us greatly with detailed bug reports and unusual test cases\&.
.SH "SEE ALSO"
.sp
\fBlttng\fR(1), \fBlttng-enable-event\fR(1), \fBlttng-list\fR(1), \fBlttng-concepts\fR(7)
